// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcrmnnzbrrepftmlywcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxjcm1ubnpicnJlcGZ0bWx5d2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNDY2OTQsImV4cCI6MjA1MDYyMjY5NH0.CcNly69isxNUpBhmmbsu3jllT-gLaBUZjcBS87cF0O0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);